[package]
name = "podcasts"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
rss = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
